spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    driver-class-name: ${DB_CLASS}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: ${REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: ${AUTH_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: id

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable: true
    default-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  main:
    allow-bean-definition-overriding: 'true'
  data:
    redis:
      host: ${R_HOST}
      port: ${R_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessTime: ${ACCESS_TIME}
  refreshTime: ${REFRESH_TIME}

server:
  port: '9040'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**